service: watercooler-express

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  runtime: python3.6

  stage: ${opt:stage}

  environment:
    TABLE_PREFIX: wce-${opt:stage}
    USERS_TABLE: ${self:provider.environment.TABLE_PREFIX}-users
    MATCHES_TABLE: ${self:provider.environment.TABLE_PREFIX}-matches
    OAUTH_ID: ${env:OAUTH_ID}
    OAUTH_SECRET: ${env:OAUTH_SECRET}
    JWT_SECRET: ${env:JWT_SECRET}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_PREFIX}-*"

functions:
  match:
    handler: lambdae/match.endpoint
    events:
      - http:
          path: match_new
          method: get

  auth:
    handler: lambdae/auth.endpoint
    events:
      - http:
          path: auth
          method: get

  auth_win:
    handler: lambdae/auth.win
    events:
      - http:
          path: win
          method: get

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: team_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    
    MatchesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MATCHES_TABLE}
        AttributeDefinitions:
          - AttributeName: team_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

custom:
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally

  pythonRequirements:
    dockerizePip: false

  customDomain:
    domainName: watercooler.express
    basePath: '' # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true