service: watercooler-express

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  runtime: python3.6 # or python3.7, supported as of November 2018

functions:
  ping:
    handler: handlers/presence.endpoint
    events:
      - http:
          path: ping
          method: get

  auth:
    handler: handlers/auth.endpoint
    environment:
      OAUTH_ID: ${env:OAUTH_ID}
      OAUTH_SECRET: ${env:OAUTH_SECRET}
      DYNAMODB_TABLE_PREFIX: ${opt:stage, self:provider.stage}
    events:
      - http:
          path: auth
          method: get

plugins:
  - serverless-domain-manager
  - serverless-python-requirements

resources:
  # DynamoDB
  - ${file(resources/dynamo-tables.yml)}

custom:
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tablePrefix: ${self:custom.stage}

  pythonRequirements:
    dockerizePip: false

  customDomain:
    domainName: watercooler.express
    basePath: '' # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true