service: watercooler-express

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: us-west-2
  runtime: python3.6

  stage: ${opt:stage, 'dev'}

  environment:
    TABLE_PREFIX: wce-${opt:stage, 'dev'}
    USERS_TABLE: ${self:provider.environment.TABLE_PREFIX}-users
    MATCHES_TABLE: ${self:provider.environment.TABLE_PREFIX}-matches
    OAUTH_ID: ${env:OAUTH_ID}
    OAUTH_SECRET: ${env:OAUTH_SECRET}
    JWT_SECRET: ${env:JWT_SECRET}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_PREFIX}-*"

functions:
  match:
    handler: lambdae/match.endpoint
    events:
      - http:
          path: match
          method: post

  auth:
    handler: lambdae/auth.endpoint
    events:
      - http:
          path: auth
          method: get

  auth_win:
    handler: lambdae/auth.make_test_users
    events:
      - http:
          path: fakes
          method: get

plugins:
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-finch
  - serverless-python-requirements

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: group_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: group_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    
    MatchesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MATCHES_TABLE}
        AttributeDefinitions:
          - AttributeName: group_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: group_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

custom:
  stage: ${self:provider.stage}

  pythonRequirements:
    dockerizePip: false

  customDomain:
    domainName: 'api.watercooler.express'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  
  client:
    bucketName: watercooler-express-client
    distributionFolder: ../frontend/public

  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
